### ISSUE TITLE
[Question] How to input TOTP ?

### ISSUE THREAD

**Issue by KaKi87** [diamondburned/slemmy#21]
Hi,

I input instance, username and password, but TOTP was greyed out.

Then I thought maybe I have to submit once before it would ask for TOTP, but I got the *missing TOTP token* error and the input remained greyed out.

What did I miss ?

Thanks

**Comment by diamondburned** [comment]
719aee4 should fix this. It seems I just forgot to re-enable TOTP.

**Comment by KaKi87** [comment]
I am now able to input the TOTP, but the error persists, despite being able to login using the official UI as well as other alternative clients. Thanks
